# frozen_string_literal: true

module Syskit
    module Runtime
        module PlanExtension
            def initialize(*, **)
                super

                @syskit_async_method = NetworkGeneration::AsyncThreaded
            end

            attr_accessor :syskit_async_method

            # The currently running resolution
            #
            # @return [NetworkGeneration::Async,nil]
            attr_accessor :syskit_current_resolution

            # True if Syskit is currently resolving a network
            def syskit_has_async_resolution?
                @syskit_current_resolution
            end

            attr_accessor :syskit_pending_forced_resolution

            def syskit_pending_forced_resolution?
                @syskit_pending_forced_resolution
            end

            # Start the resolution of the network generated by the given
            # requirement tasks
            #
            #
            # @param [Array<InstanceRequirementsTask>] requirement_tasks
            # @raise [RuntimeError] if there is already a resolution. Call
            #   {#syskit_cancel_async_resolution} first
            # @return [void]
            def syskit_start_async_resolution(requirement_tasks, **resolver_options)
                if syskit_has_async_resolution?
                    raise ArgumentError, 'an async resolution is already running, "\
                        "call #syskit_cancel_async_resolution first'
                end

                # Protect all toplevel Syskit tasks while the resolution runs
                @syskit_current_resolution = @syskit_async_method.start(
                    self, requirement_tasks, **resolver_options
                )
            end

            # Cancels the currently running resolution
            def syskit_cancel_async_resolution
                syskit_current_resolution.cancel
            end

            # True if the current resolution is finished (succcessful or not)
            def syskit_finished_async_resolution?
                syskit_current_resolution.finished?
            end

            # True if the currently running resolution is valid w.r.t. the
            # current plan's state
            #
            # @param [Set<InstanceRequirementsTask>] set of expected requirements
            #   task. It is compared with the current resolution's set of task
            #   to determine if the resolution is valid. You usually don't want
            #   to explicitely pass this.
            def syskit_valid_async_resolution?(
                current = syskit_current_resolution.default_requirement_tasks
            )
                syskit_current_resolution.valid?(current)
            end

            # Wait for the current running resolution to finish, and apply it on
            # the plan
            #
            # It is a no-op in case there are no current resolutions. Moreover,
            # cancelled resolutions are discarded and apply_requirement_modifications
            # is called again
            def syskit_join_current_resolution(raise_on_error: true)
                syskit_current_resolution&.join(raise_on_error: raise_on_error)
                @syskit_current_resolution = nil
            end

            # Apply a finished resolution on this plan
            #
            # @raise [RuntimeError] if the current resolution is not finished.
            # @return [Exception,nil] an exception that was raised during resolution,
            #   or nil if the execution finished
            def syskit_poll_async_resolution(requirement_tasks)
                syskit_current_resolution.poll(requirement_tasks)
                return unless syskit_current_resolution.finished?

                @syskit_current_resolution = nil
            end
        end

        def self.apply_requirement_modifications(
            plan, force: false, requirement_tasks: nil
        )
            if plan.syskit_has_async_resolution?
                current_requirements =
                    requirement_tasks ||
                    NetworkGeneration::Engine.discover_requirement_tasks_from_plan(plan)

                plan.syskit_pending_forced_resolution ||= force
                plan.syskit_cancel_async_resolution if force
                plan.syskit_poll_async_resolution(current_requirements)

                # The return below is needed regardless of the result of {#poll}
                #
                # If the resolution finished, it will emit resolution_success,
                # and we need the events to be actually emitted for the change detection
                # logic to work. Return to wait for one propagation cycle.
                return
            end

            force ||= plan.syskit_pending_forced_resolution?
            plan.syskit_pending_forced_resolution = false

            needs_resolution =
                force || plan.find_tasks(Syskit::InstanceRequirementsTask)
                             .running
                             .any? { |t| !t.resolution_success? }
            return unless needs_resolution

            requirement_tasks ||= NetworkGeneration::Engine
                                  .discover_requirement_tasks_from_plan(plan)
            return if requirement_tasks.empty?

            plan.syskit_start_async_resolution(requirement_tasks)
        end
    end
end

Roby::ExecutablePlan.include Syskit::Runtime::PlanExtension
