#! /usr/bin/env ruby
APP_DIR = File.expand_path(File.join('..', '..'), File.dirname(__FILE__))

require 'roby/standalone'
require 'orocos'
require 'orocos/roby'
require 'orocos/roby/app'

output_type = 'txt'
output_file = nil
parser = OptionParser.new do |opt|
    opt.banner = "Usage: scripts/orocos/instanciate_deployment [options] deployment_name"
    opt.on('--robot=NAME[,TYPE]', String, 'the robot name used as context to the deployment') do |name|
        name, type = name.split(',')
        Roby.app.robot(name, type||name)
    end
    opt.on('--output=TYPE[:file]', String, 'in what format to output the result (can be: txt, dot or svg), defaults to txt') do |output_type|
        output_type, output_file = output_type.split(':')
        output_type = output_type.downcase
        if output_type != 'txt' && !output_file
            STDERR.puts "you must specify an output file for the dot and svg outputs"
            exit(1)
        end
    end
    opt.on_tail('-h', '--help', 'this help message') do
	STDERR.puts opt
	exit
    end
end
remaining = parser.parse(ARGV)
if remaining.size != 1
    STDERR.puts parser
    exit(1)
end

Roby.filter_backtrace do
    Roby.app.setup
    Roby.app.apply_orocos_deployment(remaining.first)
end

case output_type
when "txt"
    pp Roby.app.orocos_engine
when "dot"
    File.open(output_file, 'w') do |output_io|
        output_io.puts Roby.app.orocos_engine.to_dot
    end
when "svg"
    Tempfile.open('roby_orocos_deployment') do |io|
        io.write Roby.app.orocos_engine.to_dot
        io.flush

        File.open(output_file, 'w') do |output_io|
            output_io.puts(`dot -Tsvg #{io.path}`)
        end
    end
end

